Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.define "dbserver" do |db|
    db.vm.box = "ubuntu/trusty64"
    db.vm.hostname = "dbserver"
    db.vm.network :private_network, ip: "10.10.10.10"
  end

  config.vm.define "appserver" do |app|
    app.vm.box = "ubuntu/trusty64"
    app.vm.hostname = "appserver"
    app.vm.network :private_network, ip: "10.10.10.20"
  end

  config.vm.boot_timeout = 600

end
